#include<bits/stdc++.h>
#include<conio.h>
#include<windows.h>
#include"vars.h"
#include"functions.h"
#include"useful.h"
#include"randfill.h"
#include"COWprint.h"
#include"intodo.h"
#include"end.h"
#include"cardo.h"
#include"play.h"
#include"calc.h"
